name: Deploy to GitHub Pages

on:
  push:
    branches:
      - lean4  # 如果你的工作分支不是 lean4，请修改成你的分支名，比如 main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Cache Pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install bibtool
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install bibtool -y

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: Build the website
        run: NODOWNLOAD=1 python make_site.py

      # vvvv 这是核心改动 vvvv
      - name: Upload artifact
        # 我们换回通用的 upload-artifact
        uses: actions/upload-artifact@v4
        with:
          # 并明确地将它命名为 "github-pages"
          name: github-pages
          path: ./build
      # ^^^^ 核心改动结束 ^^^^

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy from artifact
        # deploy-pages 现在可以根据明确的名称找到包裹
        uses: actions/deploy-pages@v4